language: node_js
dist: trusty
node_js:
  - 8
  - 10
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@latest --quiet
install:
  - npm ci --quiet
before_script:
  - npm i -g codecov coveralls --quiet
script:
  - npm t
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - 'cat ./coverage/lcov.info | codecov'
