language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
    - os: windows
node_js:
  - 8
  - 10
  - 11
before_script:
  - npm i -g npm@latest --quiet
  - npm i codecov coveralls --quiet
script:
  - npm cit --quiet
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - 'cat ./coverage/lcov.info | codecov'
